### ISSUE TITLE
Can't run GPU tracking inside apptainer container (with temp fix!)

### ISSUE THREAD

**Issue by CHrlS98** [scilus/containers-scilus#20]
GPU tracking won't work right out of the box when using apptainer (singularity) container.

This is related to issue https://github.com/apptainer/apptainer/issues/1752, which should be fixed by PR https://github.com/apptainer/apptainer/pull/1753. With newer nvidia drivers, OpenCL compilation requires the library nvvm which is not binded by default in Apptainer. It can be fixed by editing the `/etc/apptainer/nvliblist.conf` file. 

There is a workaround to get it to work without  modifying the config file, which we can modify on compute canada since we are not admins. Basically you need to bind the missing library yourself.

So first you need to find the path to your nvvm library. 
```
@beluga4:~$ ldconfig --print-cache | grep nvvm
	libnvidia-nvvm.so.4 (libc6,x86-64) => /usr/lib64/nvidia/libnvidia-nvvm.so.4
```
Here it is `/usr/lib64/nvidia/libnvidia-nvvm.so.4`. You need to bind it inside your container, so here we create an ENV variable:
```
@beluga4:~$ export CL_BIND_SO=/usr/lib64/nvidia/libnvidia-nvvm.so.4:/.singularity.d/libs/libnvidia-nvvm.so.4
```
Then you can run gpu tracking using `--bind $CL_BIND_SO` and `--nv` options.
```
apptainer exec --bind $PWD:/workdir --workdir /workdir --bind $CL_BIND_SO --nv containers/scilus_cuda_dev.sif scil_compute_local_tracking.py --use_gpu -v --npv 100 fodf_8.nii.gz mask.nii.gz mask.nii.gz toto_npv100.trk
```

**Comment by AlexVCaron** [comment]
Manually fixed on Compute Canada for apptainer 1.1.8 and newer
Fixed by apptainer since 1.2.4
