### ISSUE TITLE
dmriqc-flow issue

### ISSUE THREAD

**Issue by araikes** [scilus/containers-scilus#24]
Hi,

I've been using the `scilus-flows:1.5.0` image as a Singularity container for awhile to do `input_qc` and (as of yesterday) it started throwing me a Permission denied error. I don't know why it all of the sudden started doing so on our HPC nor do I see a way to debug that.

I saw that there was a permission patch here so I went and built the `dev` version of scilus-flows from Dockerhub, but when I run input_qc, I get the following error and it crashes:

```
Traceback (most recent call last):
  File "/usr/local/bin/dmriqc_generic.py", line 171, in <module>
    main()
  File "/usr/local/bin/dmriqc_generic.py", line 126, in main
    summary, stats = stats_mean_median(curr_metrics, images)
  File "/usr/local/lib/python3.10/dist-packages/dmriqcpy/analysis/stats.py", line 33, in stats_mean_median
    data = nib.load(filename).get_data()
  File "/usr/local/lib/python3.10/dist-packages/nibabel/deprecator.py", line 208, in deprecated_func
    raise exception(message)
nibabel.deprecator.ExpiredDeprecationError: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).

* deprecated from version: 3.0
* Raises <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
```

**Comment by arnaudbore** [comment]
Hi @araikes ,
Don't use the dev version, dmriqcpy still needs an old version (I've got some work to do in order to update everything).
Can you open an issue on the dmriqcpy or dmriqc_flow repo and show me your error please ?
Thank you
